### ISSUE TITLE
Question: do you use a bootstrap development environment using vagrant?

### ISSUE THREAD

**Issue by vonpupp** [it-projects-llc/odoo-development#90]
Hello,

I saw the [install] page, however I was wondering if you use or you have used Vagrant (maybe in conjunction with Buildout) in the past for development. The idea is to try to create a development environment without messing with the current environment, and try to provision everything with just one command.

If you have used Vagrant but you no longer recommend it, please let me know why.

I am [defining] my bootstrap method and I would like to put into one place the best practices that I can learn from the Odoo experts =).

Thank you very much

[install]: https://odoo-development.readthedocs.io/en/latest/admin/install.html
[defining]: https://github.com/vonpupp/odoo-module-tutorial

**Comment by yelizariev** [comment]
Hello @vonpupp,
I use docker and don't know much about other systems.
The install page may be obsolete. The latest version about my way of installation one can found in this repo: https://github.com/it-projects-llc/install-odoo

I don't have objections to alternatives \ other approaches and you are welcome to make a Pull Request with your instructions. I'll just ask to use proper section in our docs.

**Comment by vonpupp** [comment]
Thank you @yelizariev,

Currently I am using Vagrant (with virtualbox provider) + Buildout. Is working fine but I would rather have docker as provider to Vagrant, however I am having some issues to setup Ubuntu 16.04 with Docker due to dbus and systemd.

I will have a look at your repository and If I come with something useful I will gladly contribute.

Thank you very much.
